# Generated by Django 3.2 on 2022-09-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
