# Generated by Django 4.0.4 on 2022-09-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['added']},
        ),
    ]
